version: '3.8'

services:
  backend:
    build: ./backend/weatherapp
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}  # we'll define this below
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
